Repository pykalman/pykalman, pull requests merged in 2025-08, with the labels that each got.

#166 [BUG] fix time-varying transition covariance being overwritten by initial matrix in standard Kalman filter
  pykalman/standard.py
Labels: bug

#167 [DOC] Migrated all Examples to Notebooks in Documentation
  doc/source/index.rst
  doc/source/plot_filter.ipynb
  doc/source/plot_missing.ipynb
  doc/source/plot_online.ipynb
  doc/source/sine_wave.ipynb
  doc/source/unscented_kalman_filter.ipynb
  doc/source/unscented_kalman_filter_and_smoother.ipynb
Labels: documentation

#169 Release 0.10.2
  CHANGELOG.md
  README.md
  pykalman/__init__.py
  pyproject.toml
Labels: maintenance, release

#172 [MNT] `pypi` release workflow
  .github/workflows/release.yml
Labels: maintenance, release

#174 [MNT] Fix release workflow, 2nd
  .github/workflows/release.yml
Labels: maintenance, release

#171 [MNT] Check versions in wheels workflow
  .github/workflows/release.yml
Labels: maintenance
