Repository pykalman/pykalman, pull requests merged in 2025-01, with the labels that each got.

#117 [MNT] Adding pre-commit hooks
  .github/workflows/run-ci.yml
  .gitignore
  .pre-commit-config.yaml
Labels: maintenance

#120 [ENH] merge of `sktime` fork into `pykalman` - `numpy 2` compatibility, documentation, test refactor
  build_tools/changelog.py
  build_tools/fail_on_missing_init_files.sh
  pykalman/__init__.py
  pykalman/datasets/__init__.py
  pykalman/datasets/base.py
  pykalman/datasets/descr/__init__.py
  pykalman/sqrt/__init__.py
  pykalman/sqrt/bierman.py
  pykalman/sqrt/cholesky.py
  pykalman/sqrt/tests/__init__.py
  pykalman/sqrt/tests/test_bierman.py
  pykalman/sqrt/tests/test_cholesky.py
  pykalman/sqrt/tests/test_unscented.py
  pykalman/sqrt/unscented.py
  pykalman/standard.py
  pykalman/tests/__init__.py
  pykalman/tests/test_standard.py
  pykalman/tests/test_unscented.py
  pykalman/tests/ukf_tests.m
  pykalman/unscented.py
  pykalman/utils.py
  pykalman/utils_numpy.py
  pyproject.toml
Labels: enhancement, maintenance

#123 [MNT] add all-contributors file
  .all-contributorsrc
Labels: maintenance

#107 [MNT] python 3.11 compatibility - replace deprecated `inspect.getargspec`
  .all-contributorsrc
Labels: maintenance

#101 [MNT] python 3.11 compatibility - replace deprecated `inspect.getargspec`
  .all-contributorsrc
Labels: maintenance

#124 by KOLANICH [MNT] Move the metadata into `PEP-621`-compliant `pyproject.toml`
  .all-contributorsrc
  pyproject.toml
Labels: maintenance

#96 [DOC] fix simple typo, probabily -> probably
  .all-contributorsrc
  pykalman/utils.py
Labels: documentation

#125 [MNT] temporarily remove missing init file check
  .github/workflows/run-ci.yml
Labels: maintenance

#70 Fix notation wrt observation offsets
  .all-contributorsrc
  doc/source/kf_users_guide.rst
  pykalman/standard.py
Labels: documentation

#63 [MNT] python 3.11 compatibility - replace deprecated `inspect.getargspec`
  .all-contributorsrc
Labels: maintenance

#69 [ENH] Fixed variable and argument names `_em_observation_covariance`
  .all-contributorsrc
  pykalman/standard.py
Labels: enhancement

#127 [MNT] adding test matrix
  .github/workflows/release.yml
  .github/workflows/run-ci.yml
Labels: maintenance

#131 [MNT] CI element for programmatic check of missing `__init__` files
  .github/workflows/run-ci.yml
  build_tools/fail_on_missing_init_files.sh
Labels: maintenance

#130 [MNT] Clean-up of `pyproject.toml`
  LICENSE
  pyproject.toml
Labels: maintenance

#133 [DOC] improved formatting of readme preamble, new `pykalman` logo
  README.md
  doc/source/images/pykalman-logo.png
Labels: documentation

#134 [MNT] fix `pykalman` logo in README
  README.md
Labels: documentation

#136 [DOC] `pykalman` logo with name
  README.md
  doc/source/images/pykalman-logo-with-name.png
Labels: documentation

#140 [MNT] update `release.yml`
  .github/workflows/release.yml
Labels: maintenance, release

#142 License update - acknowledge pykalman developers
  LICENSE
Labels: maintenance

#141 Release 0.10.0
  CHANGELOG
  CHANGELOG.md
  README.md
  pykalman/__init__.py
  pyproject.toml
Labels: documentation

#145 [MNT] add `packaging` as explicit dependency
  pyproject.toml
Labels: maintenance

#144 [MNT] developer dependency isolation test
  .github/workflows/run-ci.yml
  pykalman/_nopytest_tests.py
Labels: maintenance

#146 Release 0.10.1
  CHANGELOG.md
  README.md
  pykalman/__init__.py
  pyproject.toml
Labels: maintenance, release

#147 [ENH] refactor `utils` module
  pykalman/utils/__init__.py
  pykalman/utils/_numpy.py
  pykalman/utils/_sklearn.py
  pykalman/utils_numpy.py
Labels: enhancement
